apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kamil
spec:
  profile:
    displayName: Kamil Markow
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: [team-b, employees]
